### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by imamsmajser** [danielkrupinski/OneByteLdr#6]
I use the latest version of Python.I start CS:GO and after that a Python scrpit.
My dll still gets detectable,what to do?

**Comment by jxian725** [comment]
Try this: https://github.com/danielkrupinski/OneByteLdr/issues/5

**Comment by xmine7890** [comment]
> Try this: #5

@jxian725 i am using pymem version 1.2 thats the issue???

**Comment by imamsmajser** [comment]
> > Try this: #5
> 
> @jxian725 i am using pymem version 1.2 thats the issue???

im using latest,but cmd opens for a second then close

**Comment by xmine7890** [comment]
@jxian725 @danielkrupinski 
i am getting this after installing 32-bit version of python and pymem 1.2 version
C:\>python OneByteLdr.py
The token does not have the specified privilege.

Traceback (most recent call last):
  File "OneByteLdr.py", line 4, in <module>
    pm = pymem.Pymem('csgo.exe')
  File "C:\Python\Python38-32\lib\site-packages\pymem\__init__.py", line 45, in __init__
    self.open_process_from_name(process_name)
  File "C:\Python\Python38-32\lib\site-packages\pymem\__init__.py", line 198, in open_process_from_name
    self.open_process_from_id(self.process_id)
  File "C:\Python\Python38-32\lib\site-packages\pymem\__init__.py", line 220, in open_process_from_id
    raise pymem.exception.CouldNotOpenProcess(self.process_id)
pymem.exception.CouldNotOpenProcess: Could not open process: 14800

**Comment by jxian725** [comment]
> > > Try this: #5
> > 
> > 
> > @jxian725 i am using pymem version 1.2 thats the issue???
> 
> im using latest,but cmd opens for a second then close

Run the python script from cmd or python.exe. not direct double clicking it so that you may see and troubleshoot token error for the failure.
Most probably is that your python missing pymem and win32api module

**Comment by jxian725** [comment]
> @jxian725 @danielkrupinski
> i am getting this after installing 32-bit version of python and pymem 1.2 version
> C:>python OneByteLdr.py
> The token does not have the specified privilege.
> 
> Traceback (most recent call last):
> File "OneByteLdr.py", line 4, in
> pm = pymem.Pymem('csgo.exe')
> File "C:\Python\Python38-32\lib\site-packages\pymem__init__.py", line 45, in **init**
> self.open_process_from_name(process_name)
> File "C:\Python\Python38-32\lib\site-packages\pymem__init__.py", line 198, in open_process_from_name
> self.open_process_from_id(self.process_id)
> File "C:\Python\Python38-32\lib\site-packages\pymem__init__.py", line 220, in open_process_from_id
> raise pymem.exception.CouldNotOpenProcess(self.process_id)
> pymem.exception.CouldNotOpenProcess: Could not open process: 14800

Just run as admin for the command. If the problem still exist you may try downgrade your pymem to v1.0 as suggested by daniel

**Comment by imamsmajser** [comment]
I have installed Python.I tried to install Pymem but cmd closed after milisecond.Same problem with bypass..

**Comment by imamsmajser** [comment]
How to run command from cmd or python?

**Comment by jxian725** [comment]
Open cmd then run:
[python.exe path] [OneByteLdr.py path]

**Comment by jxian725** [comment]
> How to run command from cmd or python?

Open cmd then run:
[python.exe path] [OneByteLdr.py path]

**Comment by imamsmajser** [comment]
invalid syntax

**Comment by imamsmajser** [comment]
Can someone record a tutorial about this?? xD

**Comment by imamsmajser** [comment]
> > How to run command from cmd or python?
> 
> Open cmd then run:
> [python.exe path] [OneByteLdr.py path]

how to install pymem?

**Comment by xmine7890** [comment]
> > > How to run command from cmd or python?
> > 
> > 
> > Open cmd then run:
> > [python.exe path] [OneByteLdr.py path]
> 
> how to install pymem?

pip install pymem in cmd

**Comment by urmommine** [comment]
> > > > How to run command from cmd or python?
> > > 
> > > 
> > > Open cmd then run:
> > > [python.exe path] [OneByteLdr.py path]
> > 
> > 
> > how to install pymem?
> 
> pip install pymem in cmd
help i got this error when try to install it
https://prnt.sc/t9bblx

**Comment by jxian725** [comment]
> > > > > How to run command from cmd or python?
> > > > 
> > > > 
> > > > Open cmd then run:
> > > > [python.exe path] [OneByteLdr.py path]
> > > 
> > > 
> > > how to install pymem?
> > 
> > 
> > pip install pymem in cmd
> > help i got this error when try to install it
> > https://prnt.sc/t9bblx

you can also install pymem manually here:
https://pypi.org/project/Pymem/#files

**Comment by KillaBoi** [comment]
> > > > > How to run command from cmd or python?
> > > > 
> > > > 
> > > > Open cmd then run:
> > > > [python.exe path] [OneByteLdr.py path]
> > > 
> > > 
> > > how to install pymem?
> > 
> > 
> > pip install pymem in cmd
> > help i got this error when try to install it
> > https://prnt.sc/t9bblx

`pip install pymem` has to be run from a normal CMD window, not a window with python running in it.

**Comment by AlexxSL** [comment]
> > @jxian725 @danielkrupinski
> > i am getting this after installing 32-bit version of python and pymem 1.2 version
> > C:>python OneByteLdr.py
> > The token does not have the specified privilege.
> > Traceback (most recent call last):
> > File "OneByteLdr.py", line 4, in
> > pm = pymem.Pymem('csgo.exe')
> > File "C:\Python\Python38-32\lib\site-packages\pymem__init__.py", line 45, in **init**
> > self.open_process_from_name(process_name)
> > File "C:\Python\Python38-32\lib\site-packages\pymem__init__.py", line 198, in open_process_from_name
> > self.open_process_from_id(self.process_id)
> > File "C:\Python\Python38-32\lib\site-packages\pymem__init__.py", line 220, in open_process_from_id
> > raise pymem.exception.CouldNotOpenProcess(self.process_id)
> > pymem.exception.CouldNotOpenProcess: Could not open process: 14800
> 
> Just run as admin for the command. If the problem still exist you may try downgrade your pymem to v1.0 as suggested by daniel

Im getting the same error. I have the latest version of python and pymem 1.0 and win32api. Still gives me the error when I try to run the OneByteLdr.py
